package stemmers

import (
	"bufio"
	"os"
	"path/filepath"
	"testing"
)

// vectorCase pairs an algorithm with the golden stems for the shared corpus.
type vectorCase struct {
	algo Algorithm
	res  string
}

// vectorCases lists the committed parity oracles: for each algorithm, the result
// of stemming testdata/corpus.txt (a CC0 OpenAlex-derived word list) with
// rust-stemmers 1.2.0, regenerated by rustgen. See testdata/NOTICE.md.
var vectorCases = []vectorCase{
	{Arabic, "res_ar.txt"},
	{Danish, "res_da.txt"},
	{Dutch, "res_nl.txt"},
	{English, "res_en.txt"},
	{Finnish, "res_fi.txt"},
	{French, "res_fr.txt"},
	{German, "res_ger.txt"},
	{Greek, "res_el.txt"},
	{Hungarian, "res_hu.txt"},
	{Italian, "res_it.txt"},
	{Norwegian, "res_no.txt"},
	{Portuguese, "res_pt.txt"},
	{Romanian, "res_ro.txt"},
	{Russian, "res_ru.txt"},
	{Spanish, "res_es.txt"},
	{Swedish, "res_sv.txt"},
	{Tamil, "res_ta.txt"},
	{Turkish, "res_tr.txt"},
}

// TestVectors is the conformance teeth: stemming every word of the shared corpus
// with each algorithm must match its golden byte-for-byte. A single divergence
// fails the build — the build/query-symmetry guarantee a stemmed term index needs.
// The goldens are rust-stemmers 1.2.0 output, so this pins Go == Rust without
// needing a Rust toolchain at test time (the live cross-check is TestRustgenParity).
func TestVectors(t *testing.T) {
	corpus := readLines(t, filepath.Join("testdata", "corpus.txt"))
	for _, tc := range vectorCases {
		t.Run(tc.res, func(t *testing.T) {
			res := readLines(t, filepath.Join("testdata", tc.res))
			if len(corpus) != len(res) {
				t.Fatalf("corpus has %d lines but %s has %d", len(corpus), tc.res, len(res))
			}
			s := New(tc.algo)
			mismatch := 0
			for i := range corpus {
				got := s.Stem(corpus[i])
				if got != res[i] {
					mismatch++
					if mismatch <= 20 {
						t.Errorf("Stem(%q) = %q, want %q", corpus[i], got, res[i])
					}
				}
			}
			if mismatch > 0 {
				t.Fatalf("%d/%d stems diverged from %s", mismatch, len(corpus), tc.res)
			}
		})
	}
}

// TestEnglishKnown spot-checks representative English stems independent of the
// vendored vectors: each step's rewrite, an exception, and invariants.
func TestEnglishKnown(t *testing.T) {
	s := New(English)
	cases := map[string]string{
		"fruitlessly":  "fruitless", // step 2 (-li) + step 4
		"consign":      "consign",   // unchanged
		"consigned":    "consign",   // step 1b
		"consignment":  "consign",   // step 4 (-ment)
		"generously":   "generous",  // a0 prefix region + -li
		"national":     "nation",    // step 2 (-ational -> -ation -> step 3/4)
		"sky":          "sky",       // exception1 invariant
		"skis":         "ski",       // exception1 rewrite
		"dying":        "die",       // exception1 rewrite
		"early":        "earli",     // exception1 rewrite
		"news":         "news",      // exception1 invariant
		"succeed":      "succeed",   // exception2 invariant
		"herring":      "herring",   // exception2 invariant
		"":             "",          // empty
		"y":            "y",         // too short to stem
		"agreed":       "agre",      // step 1b (-eed in R1) -> agree -> step 5 e? -> agre
		"feed":         "feed",      // -eed not in R1, unchanged
		"organization": "organ",     // step 2 (-ization) + step 4
	}
	for in, want := range cases {
		if got := s.Stem(in); got != want {
			t.Errorf("Stem(%q) = %q, want %q", in, got, want)
		}
	}
}

// readLines reads a file into a slice of lines (without trailing newlines).
func readLines(t *testing.T, path string) []string {
	t.Helper()
	f, err := os.Open(path)
	if err != nil {
		t.Fatalf("open %s: %v", path, err)
	}
	defer f.Close()
	var lines []string
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for sc.Scan() {
		lines = append(lines, sc.Text())
	}
	if err := sc.Err(); err != nil {
		t.Fatalf("scan %s: %v", path, err)
	}
	return lines
}
